version: '3'
services:
  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: TestPassword1
      ACCEPT_EULA: Y
  backend:
    build:
        context: .
        dockerfile: Dockerfile
    environment:
      ConnectionStrings__HEDWIG: Server=db;Database=master;User=sa;Password=TestPassword1
      WingedKeysUri: 'https://winged-keys:5050'
      CLIENT_HOST: 'http://client:3000'
      DOCKER_DEVELOPMENT: 'true'
    volumes:
      - ./src/Hedwig:/app/src/Hedwig:cached
      - ./test/HedwigTests:/app/test/HedwigTests:cached
      - ./Hedwig.sln:/app/Hedwig.sln
      - ./.editorconfig:/app/.editorconfig
      - ./entrypoint-backend.sh:/entrypoint.sh
    working_dir: /app/src/Hedwig
    ports:
      - 5000:5000
      - 5001:5001
    entrypoint:
      - sh
      - /entrypoint.sh
    depends_on:
      - db
      - winged-keys
  client:
    image: node:12
    volumes:
      - ./src/Hedwig/ClientApp:/home/node/app:cached
      - ./entrypoint-client.sh:/entrypoint.sh
    working_dir: /home/node/app
    ports:
      - 9009:9009
    entrypoint:
      - sh
      - /entrypoint.sh
    environment:
      HOST: '0.0.0.0'
      E2E_GRID_URL: 'http://selenium-hub:4444/wd/hub'
      E2E_CLIENT_URL: 'https://backend:5001'
      BROWSERSTACK_LOCAL: 'true'
      BROWSERSTACK_USERNAME: ${BROWSERSTACK_USERNAME}
      BROWSERSTACK_ACCESS_KEY: ${BROWSERSTACK_ACCESS_KEY}
    depends_on:
      - backend
      - winged-keys
  winged-keys-db:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: TestPassword1
      ACCEPT_EULA: Y
  winged-keys:
    build:
        context: .
        dockerfile: ./winged-keys/Dockerfile
    environment:
      ConnectionStrings__WINGEDKEYS: Server=winged-keys-db;Database=master;User=sa;Password=TestPassword1
    volumes:
      - ./winged-keys/src/WingedKeys:/app/src/WingedKeys:cached
      # - ./winged-keys/tests/WingedKeysTests:/app/tests/WingedKeysTests:cached
      - ./winged-keys/entrypoint.sh:/entrypoint.sh
    working_dir: /app/src/WingedKeys
    ports:
      - 5050:5050
    entrypoint:
      - sh
      - /entrypoint.sh
    depends_on:
    - winged-keys-db

  # Selenium containers
  # backend-for-selenium:
  #   build:
  #       context: .
  #       dockerfile: selenium.Dockerfile
  #   environment:
  #     ConnectionStrings__HEDWIG: Server=db;Database=master;User=sa;Password=TestPassword1
  #     WingedKeysUri: 'https://winged-keys:5050'
  #     CLIENT_HOST: 'http://client-for-selenium:3000'
  #     DOCKER_DEVELOPMENT: 'true'
  #   volumes:
  #     - ./entrypoint-backend.sh:/entrypoint.sh
  #   working_dir: /app/src/Hedwig
  #   entrypoint:
  #     - sh
  #     - /entrypoint.sh
  # client-for-selenium:
  #   image: node:12
  #   volumes:
  #     - ./src/Hedwig/ClientApp:/home/node/app:cached
  #     - ./entrypoint-client.sh:/entrypoint.sh
  #   working_dir: /home/node/app
  #   entrypoint:
  #     - sh
  #     - /entrypoint.sh
  #   environment:
  #     REACT_APP_DEFAULT_WINGED_KEYS_URL: 'https://winged-keys:5050'
  selenium-hub:
    image: selenium/hub
    container_name: selenium-hub
    ports:
      - 4444:4444
  # e2e-chrome:
  #   image: selenium/node-chrome
  #   depends_on:
  #     - selenium-hub
  #   environment:
  #     - HUB_HOST=selenium-hub
  #     - HUB_PORT=4444
  # e2e-firefox:
  #   image: selenium/node-firefox
  #   depends_on:
  #     - selenium-hub
  #   environment:
  #     - HUB_HOST=selenium-hub
  #     - HUB_PORT=4444
  # Uncomment these (and comment the above e2e-* containers) to allow for VNC connection to the automated browser
  e2e-chrome-debug:
    image: selenium/node-chrome-debug
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    ports:
      - 5900:5900
  e2e-firefox-debug:
    image: selenium/node-firefox-debug
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
    ports:
      - 5901:5900
